spring:
  profiles:
    include: thirdparty-mp-sdk-dev
  datasource:
    url: jdbc:mysql://192.168.1.202:7125/jlyzparty
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ENC(ETWygv0bn5NoUv2V96KGbXgPbzxqxvRz)
  thymeleaf:
    prefix: classpath:/templates/