spring:
  profiles:
    include: thirdparty-mp-sdk-dev
  datasource:
    url: jdbc:mysql://180.169.82.28:3336/jlyzparty?characterEncoding=utf-8&&allowMultiQueries=true&&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
    username: dlbroot
    password: ENC(ETWygv0bn5NoUv2V96KGbXgPbzxqxvRz)
  thymeleaf:
    prefix: classpath:/templates/
mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - tk.mybatis.springboot.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
pic: 
  rootPath: C:\\upload\\picture
  