spring:
  profiles:
    include: thirdparty-mp-sdk-dev
  datasource:
    url: jdbc:mysql://180.169.82.28:7125/jlyzparty?characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ENC(ETWygv0bn5NoUv2V96KGbXgPbzxqxvRz)
  thymeleaf:
    prefix: classpath:/templates/
pic: 
  rootPath: C:\\upload\\picture